services:
  postgresql:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: pzi
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/new-schema/db/migrations:/docker-entrypoint-initdb.d
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d pzi"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data: