name: Build and Publish pzi-webapp

on:
  push:
    branches:
      - main
    paths:
      - pzi-webapp/**
  workflow_dispatch:

env:
  DOCKER_REGISTRY_URL: 'elaniton.azurecr.io'
  DOCKER_IMAGE_NAME: 'pzi/web'

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: pzi-webapp

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install git version
        uses: gittools/actions/gitversion/setup@v1.1.1
        with:
          versionSpec: '5.x'

      - name: Determine Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v1.1.1

      - name: Set-up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm ci
      
      - name: Typecheck and Test
        run: |
          npm run typecheck
          npm test

      - name: Build app
        run: npm run build
      
      - name: Export version file
        run: echo '${{ steps.gitversion.outputs.semVer }}' > build/client/version.txt

      - name: Build docker image
        run: docker build . --file Dockerfile --build-arg APP_VERSION_FULL=${{ steps.gitversion.outputs.fullSemVer }} --build-arg APP_VERSION_SHORT=${{ steps.gitversion.outputs.semVer }} --tag $DOCKER_REGISTRY_URL/$DOCKER_IMAGE_NAME:${{ steps.gitversion.outputs.semVer }}

      - name: Push docker image to ACR
        run: |
          docker login -u ${{secrets.ACR_USER}} -p ${{secrets.ACR_PASSWORD}} $DOCKER_REGISTRY_URL
          docker push $DOCKER_REGISTRY_URL/$DOCKER_IMAGE_NAME:${{ steps.gitversion.outputs.semVer }}
